# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "Card": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://sh4062.github.io/python_00/"

git_url = "https://github.com/sh4062/python_00/tree/master/"

def custom_doc_links(name): return None
